import { config } from '@vue/test-utils';
import { vi } from 'vitest';

// Mock Leaflet globally
vi.mock('leaflet', () => ({
	default: {
		map: vi.fn(() => ({
			setView: vi.fn(),
			getZoom: vi.fn(() => 13),
			getCenter: vi.fn(() => ({ lat: 0, lng: 0 })),
			setZoom: vi.fn(),
			on: vi.fn(),
			off: vi.fn(),
			remove: vi.fn(),
			removeLayer: vi.fn(),
			addLayer: vi.fn(),
			hasLayer: vi.fn(() => true),
			fitBounds: vi.fn(),
			flyTo: vi.fn(),
			panTo: vi.fn(),
			invalidateSize: vi.fn(),
			getBounds: vi.fn(() => ({
				getNorthEast: vi.fn(() => ({ lat: 1, lng: 1 })),
				getSouthWest: vi.fn(() => ({ lat: -1, lng: -1 })),
			})),
			getContainer: vi.fn(() => document.createElement('div')),
			getPane: vi.fn(() => document.createElement('div')),
			createPane: vi.fn(),
			getSize: vi.fn(() => ({ x: 800, y: 600 })),
		})),
		tileLayer: vi.fn(() => ({
			addTo: vi.fn(() => ({
				remove: vi.fn(),
				setUrl: vi.fn(),
				setOpacity: vi.fn(),
				setZIndex: vi.fn(),
				redraw: vi.fn(),
			})),
		})),
		// tileLayer.wms is accessed as L.tileLayer.wms() - static method
		tileLayerWMS: undefined,
		marker: vi.fn((latlng, options) => ({
			setLatLng: vi.fn(),
			getLatLng: vi.fn(() => ({ lat: latlng[0], lng: latlng[1] })),
			setZIndexOffset: vi.fn(),
			setOpacity: vi.fn(),
			on: vi.fn(),
			off: vi.fn(),
			addTo: vi.fn(),
			remove: vi.fn(),
			bindPopup: vi.fn(),
			unbindPopup: vi.fn(),
			openPopup: vi.fn(),
			closePopup: vi.fn(),
			bindTooltip: vi.fn(),
			unbindTooltip: vi.fn(),
			openTooltip: vi.fn(),
			closeTooltip: vi.fn(),
			dragging: {
				enable: vi.fn(),
				disable: vi.fn(),
			},
			options: options || {},
		})),
		circle: vi.fn((latlng, radius, options) => ({
			setLatLng: vi.fn(),
			getLatLng: vi.fn(() => ({ lat: latlng[0], lng: latlng[1] })),
			setRadius: vi.fn(),
			getRadius: vi.fn(() => radius),
			setStyle: vi.fn(),
			on: vi.fn(),
			off: vi.fn(),
			addTo: vi.fn(),
			remove: vi.fn(),
			bindPopup: vi.fn(),
			bindTooltip: vi.fn(),
			options: options || {},
		})),
		circleMarker: vi.fn((latlng, options) => ({
			setLatLng: vi.fn(),
			getLatLng: vi.fn(() => ({ lat: latlng[0], lng: latlng[1] })),
			setRadius: vi.fn(),
			setStyle: vi.fn(),
			on: vi.fn(),
			off: vi.fn(),
			addTo: vi.fn(),
			remove: vi.fn(),
			bindPopup: vi.fn(),
			bindTooltip: vi.fn(),
			options: options || {},
		})),
		polygon: vi.fn((latlngs, options) => ({
			setLatLngs: vi.fn(),
			getLatLngs: vi.fn(() => latlngs),
			setStyle: vi.fn(),
			on: vi.fn(),
			off: vi.fn(),
			addTo: vi.fn(),
			remove: vi.fn(),
			bindPopup: vi.fn(),
			bindTooltip: vi.fn(),
			options: options || {},
		})),
		polyline: vi.fn((latlngs, options) => ({
			setLatLngs: vi.fn(),
			getLatLngs: vi.fn(() => latlngs),
			setStyle: vi.fn(),
			on: vi.fn(),
			off: vi.fn(),
			addTo: vi.fn(),
			remove: vi.fn(),
			bindPopup: vi.fn(),
			bindTooltip: vi.fn(),
			options: options || {},
		})),
		rectangle: vi.fn((bounds, options) => ({
			setBounds: vi.fn(),
			getBounds: vi.fn(() => bounds),
			setStyle: vi.fn(),
			on: vi.fn(),
			off: vi.fn(),
			addTo: vi.fn(),
			remove: vi.fn(),
			bindPopup: vi.fn(),
			bindTooltip: vi.fn(),
			options: options || {},
		})),
		geoJSON: vi.fn((data, options) => ({
			addData: vi.fn(),
			resetStyle: vi.fn(),
			setStyle: vi.fn(),
			on: vi.fn(),
			off: vi.fn(),
			addTo: vi.fn(),
			remove: vi.fn(),
			bindPopup: vi.fn(),
			bindTooltip: vi.fn(),
			options: options || {},
		})),
		layerGroup: vi.fn((layers, options) => ({
			addLayer: vi.fn(),
			removeLayer: vi.fn(),
			hasLayer: vi.fn(() => true),
			clearLayers: vi.fn(),
			getLayers: vi.fn(() => layers || []),
			on: vi.fn(),
			off: vi.fn(),
			addTo: vi.fn(),
			remove: vi.fn(),
			options: options || {},
		})),
		featureGroup: vi.fn((layers, options) => ({
			addLayer: vi.fn(),
			removeLayer: vi.fn(),
			setStyle: vi.fn(),
			bringToFront: vi.fn(),
			bringToBack: vi.fn(),
			getBounds: vi.fn(() => ({
				getNorthEast: vi.fn(() => ({ lat: 1, lng: 1 })),
				getSouthWest: vi.fn(() => ({ lat: -1, lng: -1 })),
			})),
			on: vi.fn(),
			off: vi.fn(),
			addTo: vi.fn(),
			remove: vi.fn(),
			bindPopup: vi.fn(),
			bindTooltip: vi.fn(),
			options: options || {},
		})),
		popup: vi.fn((options) => ({
			setLatLng: vi.fn(),
			getLatLng: vi.fn(() => ({ lat: 0, lng: 0 })),
			setContent: vi.fn(),
			getContent: vi.fn(),
			update: vi.fn(),
			openOn: vi.fn(),
			openPopup: vi.fn(),
			closePopup: vi.fn(),
			remove: vi.fn(),
			on: vi.fn(),
			off: vi.fn(),
			options: options || {},
		})),
		tooltip: vi.fn((options) => ({
			setLatLng: vi.fn(),
			getLatLng: vi.fn(() => ({ lat: 0, lng: 0 })),
			setContent: vi.fn(),
			getContent: vi.fn(),
			update: vi.fn(),
			openOn: vi.fn(),
			openTooltip: vi.fn(),
			closeTooltip: vi.fn(),
			remove: vi.fn(),
			on: vi.fn(),
			off: vi.fn(),
			options: options || {},
		})),
		icon: vi.fn((options) => ({
			options: options || {},
			createIcon: vi.fn(() => document.createElement('div')),
			createShadow: vi.fn(() => document.createElement('div')),
		})),
		divIcon: vi.fn((options) => ({
			options: options || {},
			createIcon: vi.fn(() => document.createElement('div')),
			createShadow: vi.fn(() => null),
		})),
		point: vi.fn((x, y, round) => ({ x, y, round })),
		bounds: vi.fn((a, b) => ({
			getNorthEast: vi.fn(() => a),
			getSouthWest: vi.fn(() => b || a),
			getCenter: vi.fn(() => ({ lat: 0, lng: 0 })),
			contains: vi.fn(() => true),
			intersects: vi.fn(() => true),
		})),
		latLng: vi.fn((lat, lng) => ({ lat, lng })),
		latLngBounds: vi.fn((sw, ne) => ({
			getSouthWest: vi.fn(() => sw),
			getNorthEast: vi.fn(() => ne),
			getCenter: vi.fn(() => ({ lat: (sw.lat + ne.lat) / 2, lng: (sw.lng + ne.lng) / 2 })),
		})),
		DomEvent: {
			on: vi.fn(),
			off: vi.fn(),
			stopPropagation: vi.fn(),
			preventDefault: vi.fn(),
		},
		DomUtil: {
			get: vi.fn((id) => document.getElementById(id)),
			getStyle: vi.fn(() => ''),
			create: vi.fn((tagName, className) => {
				const el = document.createElement(tagName);
				if (className) el.className = className;
				return el;
			}),
			remove: vi.fn(),
			empty: vi.fn(),
			toFront: vi.fn(),
			toBack: vi.fn(),
			hasClass: vi.fn(() => false),
			addClass: vi.fn(),
			removeClass: vi.fn(),
			setClass: vi.fn(),
			getClass: vi.fn(() => ''),
			setOpacity: vi.fn(),
			testProp: vi.fn(() => ''),
			setTransform: vi.fn(),
			setPosition: vi.fn(),
			getPosition: vi.fn(() => ({ x: 0, y: 0 })),
			disableTextSelection: vi.fn(),
			enableTextSelection: vi.fn(),
			disableImageDrag: vi.fn(),
			enableImageDrag: vi.fn(),
			preventOutline: vi.fn(),
			restoreOutline: vi.fn(),
		},
		Util: {
			extend: vi.fn((dest, ...sources) => Object.assign(dest, ...sources)),
			create: vi.fn((proto, props) => Object.create(proto, props)),
			bind: vi.fn((fn, ...args) => fn.bind(null, ...args)),
			stamp: vi.fn((obj) => {
				if (!obj._leaflet_id) obj._leaflet_id = ++Util.lastId;
				return obj._leaflet_id;
			}),
			throttle: vi.fn((fn, time, context) => fn),
			wrapNum: vi.fn((x, range, includeMax) => x),
			falseFn: vi.fn(() => false),
			formatNum: vi.fn((num, digits) => Number(num.toFixed(digits || 5))),
			trim: vi.fn((str) => str.trim()),
			splitWords: vi.fn((str) => str.split(/\s+/)),
			setOptions: vi.fn((obj, options) => {
				obj.options = { ...obj.options, ...options };
				return obj.options;
			}),
			getParamString: vi.fn((obj, existingUrl, uppercase) => ''),
			template: vi.fn((str, data) => str.replace(/\{ *(\w+) *\}/g, (str, key) => data[key] || '')),
			isArray: vi.fn((obj) => Array.isArray(obj)),
			emptyImageUrl: 'data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=',
		},
		Browser: {
			svg: true,
			canvas: true,
			vml: false,
			webkit: true,
			gecko: false,
			ie: false,
			ie6: false,
			ie7: false,
			ielt9: false,
			edge: false,
			opera: false,
			android: false,
			android23: false,
			chrome: true,
			safari: false,
			win: false,
			ie3d: false,
			webkit3d: true,
			gecko3d: false,
			opera3d: false,
			any3d: true,
			mobile: false,
			mobileWebkit: false,
			mobileWebkit3d: false,
			mobileOpera: false,
			mobileGecko: false,
			touch: false,
			msPointer: false,
			pointer: false,
			retina: false,
			passiveEvents: true,
			nativeAnim: true,
		},
		Control: {
			Zoom: vi.fn(),
			Attribution: vi.fn(),
			Scale: vi.fn(),
			Layers: vi.fn(),
		},
		control: {
			zoom: vi.fn(() => ({
				addTo: vi.fn(),
			})),
			scale: vi.fn(() => ({
				addTo: vi.fn(),
			})),
			attribution: vi.fn(() => ({
				addTo: vi.fn(),
			})),
			layers: vi.fn(() => ({
				addTo: vi.fn(),
			})),
		},
	},
}));

// Extend expect with Vue Test Utils matchers
config.global.stubs = {
	transition: false,
	'transition-group': false,
};

// Global mocks
global.ResizeObserver = vi.fn().mockImplementation(() => ({
	observe: vi.fn(),
	unobserve: vi.fn(),
	disconnect: vi.fn(),
}));

// Mock matchMedia
global.matchMedia = vi.fn().mockImplementation((query) => ({
	matches: false,
	media: query,
	onchange: null,
	addListener: vi.fn(),
	removeListener: vi.fn(),
	addEventListener: vi.fn(),
	removeEventListener: vi.fn(),
	dispatchEvent: vi.fn(),
}));
